<template lang="html">
  <xui-container>
    <xui-table inverted>
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="red" inverted>
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="orange" inverted>
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="yellow" inverted>
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="olive" inverted>
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="green" inverted>
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="teal" inverted>
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="blue" inverted>
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="violet" inverted>
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="purple" inverted>
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="pink" inverted>
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="grey" inverted>
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="black" inverted>
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
  </xui-container>
</template>

<script>
export default {
  name: 'TableColoredExample',
};
</script>
