<template lang="html">
  <xui-container>
    <xui-table color="red">
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="orange">
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="yellow">
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="olive">
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="green">
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="teal">
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="blue">
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="violet">
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="purple">
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="pink">
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="grey">
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
    <xui-table color="black">
      <xui-table-header>
        <xui-table-row>
          <xui-table-header-cell>Food</xui-table-header-cell>
          <xui-table-header-cell>Calories</xui-table-header-cell>
          <xui-table-header-cell>Protein</xui-table-header-cell>
        </xui-table-row>
      </xui-table-header>
      <xui-table-body>
        <xui-table-row>
          <xui-table-cell>Apples</xui-table-cell>
          <xui-table-cell>200</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
        <xui-table-row>
          <xui-table-cell>Orange</xui-table-cell>
          <xui-table-cell>310</xui-table-cell>
          <xui-table-cell>0g</xui-table-cell>
        </xui-table-row>
      </xui-table-body>
    </xui-table>
  </xui-container>
</template>

<script>
export default {
  name: 'TableColoredExample',
};
</script>
